logo: "https://cdn.huoyijie.cn/ab/static/huoyijie-cn-white.png"
link: "https://huoyijie.cn"
icon: "https://cdn.huoyijie.cn/ab/static/huoyijie.png"
name: "Keynote"
title: "SHOW YOU THE CODE"
author: "huoyijie"
desc: "SHOW YOU THE CODE"
summry: "我在平时的开发过程中，总会遇到一些没见过的问题，就需要 Google 检索技术资料，然后逐渐理解和解决问题。把问题解决的过程和思路记录下来，后面再查阅时会很方便，而且对后来的学习者也是有帮助的。我也会尝试记录一些实践过的编程技巧，不定期记录更新。"
copyright: "huoyijie.cn"
